apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: fts
      defaultBucket: fts
      tlsSkipVerify: true
      timeout: 3600
    secureJsonData:
      token: fts-token-change-me
    isDefault: true
    editable: true
