{
 "title": "FTM Stats Dashboard",
 "tags": [
  "fts",
  "ftm",
  "stats"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device1",
    "label": "Device 1",
    "query": "import \"array\"\n\ndevices = from(bucket: \"fts\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"ftm\" or r._measurement == \"ftm_stats\" or r._measurement == \"crm_stats\")\n  |> keep(columns: [\"device\"])\n  |> distinct(column: \"device\")\n\nnone_option = array.from(rows: [{device: \"None\"}])\n\nunion(tables: [none_option, devices])\n  |> sort(columns: [\"device\"])"
   },
   {
    "name": "device2",
    "label": "Device 2",
    "query": "import \"array\"\n\ndevices = from(bucket: \"fts\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"ftm\" or r._measurement == \"ftm_stats\" or r._measurement == \"crm_stats\")\n  |> keep(columns: [\"device\"])\n  |> distinct(column: \"device\")\n\nnone_option = array.from(rows: [{device: \"None\"}])\n\nunion(tables: [none_option, devices])\n  |> sort(columns: [\"device\"])"
   },
   {
    "name": "experiment",
    "label": "Exp",
    "query": "from(bucket: \"fts\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"experiments\")\n  |> filter(fn: (r) => r.type == \"start\")\n  |> keep(columns: [\"_time\", \"experiment\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"experiment\")\n  |> keep(columns: [\"experiment\"])"
   },
   {
    "name": "event_from",
    "label": "From",
    "query": "from(bucket: \"fts\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"experiments\")\n  |> filter(fn: (r) => r.experiment == \"${experiment}\")\n  |> filter(fn: (r) => r._field == \"description\")\n  |> sort(columns: [\"_time\"])\n  |> unique(column: \"_value\")\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "event_to",
    "label": "To",
    "query": "import \"array\"\n\nevents = from(bucket: \"fts\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"experiments\")\n  |> filter(fn: (r) => r.experiment == \"${experiment}\")\n  |> filter(fn: (r) => r._field == \"description\")\n  |> sort(columns: [\"_time\"])\n  |> unique(column: \"_value\")\n  |> keep(columns: [\"_value\"])\n\nnow_option = array.from(rows: [{_value: \"now\"}])\n\nunion(tables: [events, now_option])"
   },
   {
    "name": "exp_start",
    "query": "from(bucket: \"fts\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"experiments\")\n  |> filter(fn: (r) => r.experiment == \"${experiment}\")\n  |> filter(fn: (r) => r._field == \"description\")\n  |> filter(fn: (r) => r._value == \"${event_from}\")\n  |> group()\n  |> first()\n  |> map(fn: (r) => ({_value: string(v: uint(v: r._time) / uint(v: 1000000))}))"
   },
   {
    "name": "exp_end",
    "query": "import \"array\"\n\nevent_time = from(bucket: \"fts\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"experiments\")\n  |> filter(fn: (r) => r.experiment == \"${experiment}\")\n  |> filter(fn: (r) => r._field == \"description\")\n  |> filter(fn: (r) => r._value == \"${event_to}\")\n  |> group()\n  |> last()\n  |> map(fn: (r) => ({_value: string(v: uint(v: r._time) / uint(v: 1000000) + uint(v: 1000))}))\n\nnow_time = array.from(rows: [{_value: \"now\"}])\n  |> filter(fn: (r) => \"${event_to}\" == \"now\")\n\nunion(tables: [event_time, now_time])\n  |> first()"
   }
  ]
 },
 "panels": [
  {
   "title": "${device1} -FTM Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device1:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "${device2} -FTM Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device2:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "${device1} -FTM Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device1:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "${device2} -FTM Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device2:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "${device1} -RSSI (Avg/Min/Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device1:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi_avg\" or r[\"_field\"] == \"rssi_min\" or r[\"_field\"] == \"rssi_max\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "${device2} -RSSI (Avg/Min/Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device2:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi_avg\" or r[\"_field\"] == \"rssi_min\" or r[\"_field\"] == \"rssi_max\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "${device1} -RTT (Avg/Min/Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device1:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"rtt_avg_ps\" or r[\"_field\"] == \"rtt_min_ps\" or r[\"_field\"] == \"rtt_max_ps\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "${device2} -RTT (Avg/Min/Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device2:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"rtt_avg_ps\" or r[\"_field\"] == \"rtt_min_ps\" or r[\"_field\"] == \"rtt_max_ps\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "${device1} - RSSI Distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device1:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi_avg\")"
    }
   ]
  },
  {
   "title": "${device2} - RSSI Distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device2:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi_avg\")"
    }
   ]
  },
  {
   "title": "${device1} - RTT Distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device1:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"rtt_avg_ps\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000.0}))"
    }
   ]
  },
  {
   "title": "${device2} - RTT Distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"fts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftm_stats\")\n  |> filter(fn: (r) => r[\"device\"] =~ /^${device2:regex}$/)\n  |> filter(fn: (r) => r[\"_field\"] == \"rtt_avg_ps\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000.0}))"
    }
   ]
  }
 ]
}